### ISSUE TITLE
Detail about VGG16 backbone model architecture

### ISSUE THREAD

**Issue by bominn** [AICyberTeam/OSCD-datasets#2]
Hi, thanks for sharing your work.

I try to implement the model described in paper.
I find in Sec. 5.9.2 Parameter analysis, the number of parameters in VGG16 backbone is about 48M.
However, the number of VGG16 classification network already have about 138M
[post](https://towardsdatascience.com/the-w3h-of-alexnet-vggnet-resnet-and-inception-7baaaecccc96)
So can you give some detailed model architecture, thanks.

**Comment by AICyberTeam** [comment]
@bominn   Thank you for your interests. The detailed model architecture is provided in Section 4 and Section 5.4 in our paper. The reduction in the number of parameters in our backbone is because that the last pool layer and all the fully-connected layers are removed.

**Comment by bominn** [comment]
Thank for your quick reply.
